# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Experience
    url: experience/
    weight: 10
  - name: Portfolio
    url: /#portfolio
    weight: 20
  - name: Papers & Presentations
    url: publication/
    weight: 30
  # - name: Teaching
    # url: teaching/
    # weight: 40
  # - name: News
    # ur - l: /#news
    # weight: 60

