[build]
  # Use ONE command (pick your preferred Pagefind flag style)
  # Option A (recommended syntax):
  # commandmmand = "hugo --gc --minify -b $URL && npm_config_yes=true npx pagefind --site \"public\""
  # Option B (keep your existing style):
  command = "hugo --gc --minify -b $URL && npx pagefind --source 'public'"

  publish = "public"

[build.environment]
  # Pin versions so Netlify doesn't jump to breaking-newer ones
  HUGO_VERSION = "0.111.3"   # or keep "0.108.0" if that’s what worked before
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "18"        # or "20"; avoids Node 22 surprises with Pagefind

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
